// Dies habe ich (JLA) am 2022-03-08 in einer Telko mit Monika Huber und Thomas Bellebaum gesehen... (AISEC)
let test = {
    "issuer":                                           "https://daps.aisec.fraunhofer.de",
    "authorization_endpoint":                           "https://daps.aisec.fraunhofer.de/v3/authorize",
    "token_endpoint":                                   "https://daps.aisec.fraunhofer.de/v3/token",
    "jwks_uri":                                         "https://daps.aisec.fraunhofer.de/.well-known/jwks.json",
    "scopes_supported":                                 ["profile", "email", "address", "phone", "omejdn:api", "omejdn:admin", "idsc:IDS_CONNECTOR_ATTRIBUTES_ALL", "certgen"],
    "response_types_supported":                         ["code"],
    "response_modes_supported":                         ["query", "fragment", "form_post"],
    "grant_types_supported":                            ["authorization_code", "client_credentials"],
    "token_endpoint_auth_methods_supported":            ["none", "private_key_jwt"],
    "token_endpoint_auth_signing_alg_values_supported": ["RS256", "RS512", "ES256", "ES512"],
    "service_documentation":                            "https://github.com/Fraunhofer-AISEC/omejdn-server/wiki",
    "ui_locales_supported":                             [],
    "code_challenge_methods_supported":                 ["S256"],
    "tls_client_certificate_bound_access_tokens":       false,
    "mtls_endpoint_aliases":                            {},
    "require_signed_request_object":                    true,
    "pushed_authorization_request_endpoint":            "https://daps.aisec.fraunhofer.de/v3/par",
    "require_pushed_authorization_requests":            false,
    "authorization_response_iss_parameter_supported":   true,
    "userinfo_endpoint":                                "https://daps.aisec.fraunhofer.de/v3/userinfo",
    "acr_values_supported":                             [],
    "subject_types_supported":                          "public",
    "id_token_signing_alg_values_supported":            "RS256",
    "id_token_encryption_alg_values_supported":         ["none"],
    "id_token_encryption_enc_values_supported":         ["none"],
    "userinfo_signing_alg_values_supported":            ["none"],
    "userinfo_encryption_alg_values_supported":         ["none"],
    "userinfo_encryption_enc_values_supported":         ["none"],
    "request_object_signing_alg_values_supported":      ["RS256", "RS512", "ES256", "ES512"],
    "request_object_encryption_alg_values_supported":   ["none"],
    "request_object_encryption_enc_values_supported":   ["none"],
    "display_values_supported":                         ["page"],
    "claim_types_supported":                            ["normal"],
    "claims_supported":                                 [],
    "claims_locales_supported":                         [],
    "claims_parameter_supported":                       true,
    "request_parameter_supported":                      true,
    "request_uri_parameter_supported":                  true,
    "require_request_uri_registration":                 true,
    "signed_metadata":                                  "eyJraWQiOiJUQ1VGZUNOYXphbEtIZzlLenJ6TElBelJXVE1ERFdTYTdMY005WndITXlvIiwiYWxnIjoiUlMyNTYifQ.eyJpc3N1ZXIiOiJodHRwczovL2RhcHMuYWlzZWMuZnJhdW5ob2Zlci5kZSIsImF1dGhvcml6YXRpb25fZW5kcG9pbnQiOiJodHRwczovL2RhcHMuYWlzZWMuZnJhdW5ob2Zlci5kZS92My9hdXRob3JpemUiLCJ0b2tlbl9lbmRwb2ludCI6Imh0dHBzOi8vZGFwcy5haXNlYy5mcmF1bmhvZmVyLmRlL3YzL3Rva2VuIiwiandrc191cmkiOiJodHRwczovL2RhcHMuYWlzZWMuZnJhdW5ob2Zlci5kZS8ud2VsbC1rbm93bi9qd2tzLmpzb24iLCJzY29wZXNfc3VwcG9ydGVkIjpbInByb2ZpbGUiLCJlbWFpbCIsImFkZHJlc3MiLCJwaG9uZSIsIm9tZWpkbjphcGkiLCJvbWVqZG46YWRtaW4iLCJpZHNjOklEU19DT05ORUNUT1JfQVRUUklCVVRFU19BTEwiLCJjZXJ0Z2VuIl0sInJlc3BvbnNlX3R5cGVzX3N1cHBvcnRlZCI6WyJjb2RlIl0sInJlc3BvbnNlX21vZGVzX3N1cHBvcnRlZCI6WyJxdWVyeSIsImZyYWdtZW50IiwiZm9ybV9wb3N0Il0sImdyYW50X3R5cGVzX3N1cHBvcnRlZCI6WyJhdXRob3JpemF0aW9uX2NvZGUiLCJjbGllbnRfY3JlZGVudGlhbHMiXSwidG9rZW5fZW5kcG9pbnRfYXV0aF9tZXRob2RzX3N1cHBvcnRlZCI6WyJub25lIiwicHJpdmF0ZV9rZXlfand0Il0sInRva2VuX2VuZHBvaW50X2F1dGhfc2lnbmluZ19hbGdfdmFsdWVzX3N1cHBvcnRlZCI6WyJSUzI1NiIsIlJTNTEyIiwiRVMyNTYiLCJFUzUxMiJdLCJzZXJ2aWNlX2RvY3VtZW50YXRpb24iOiJodHRwczovL2dpdGh1Yi5jb20vRnJhdW5ob2Zlci1BSVNFQy9vbWVqZG4tc2VydmVyL3dpa2kiLCJ1aV9sb2NhbGVzX3N1cHBvcnRlZCI6W10sImNvZGVfY2hhbGxlbmdlX21ldGhvZHNfc3VwcG9ydGVkIjpbIlMyNTYiXSwidGxzX2NsaWVudF9jZXJ0aWZpY2F0ZV9ib3VuZF9hY2Nlc3NfdG9rZW5zIjpmYWxzZSwibXRsc19lbmRwb2ludF9hbGlhc2VzIjp7fSwicmVxdWlyZV9zaWduZWRfcmVxdWVzdF9vYmplY3QiOnRydWUsInB1c2hlZF9hdXRob3JpemF0aW9uX3JlcXVlc3RfZW5kcG9pbnQiOiJodHRwczovL2RhcHMuYWlzZWMuZnJhdW5ob2Zlci5kZS92My9wYXIiLCJyZXF1aXJlX3B1c2hlZF9hdXRob3JpemF0aW9uX3JlcXVlc3RzIjpmYWxzZSwiYXV0aG9yaXphdGlvbl9yZXNwb25zZV9pc3NfcGFyYW1ldGVyX3N1cHBvcnRlZCI6dHJ1ZSwidXNlcmluZm9fZW5kcG9pbnQiOiJodHRwczovL2RhcHMuYWlzZWMuZnJhdW5ob2Zlci5kZS92My91c2VyaW5mbyIsImFjcl92YWx1ZXNfc3VwcG9ydGVkIjpbXSwic3ViamVjdF90eXBlc19zdXBwb3J0ZWQiOiJwdWJsaWMiLCJpZF90b2tlbl9zaWduaW5nX2FsZ192YWx1ZXNfc3VwcG9ydGVkIjoiUlMyNTYiLCJpZF90b2tlbl9lbmNyeXB0aW9uX2FsZ192YWx1ZXNfc3VwcG9ydGVkIjpbIm5vbmUiXSwiaWRfdG9rZW5fZW5jcnlwdGlvbl9lbmNfdmFsdWVzX3N1cHBvcnRlZCI6WyJub25lIl0sInVzZXJpbmZvX3NpZ25pbmdfYWxnX3ZhbHVlc19zdXBwb3J0ZWQiOlsibm9uZSJdLCJ1c2VyaW5mb19lbmNyeXB0aW9uX2FsZ192YWx1ZXNfc3VwcG9ydGVkIjpbIm5vbmUiXSwidXNlcmluZm9fZW5jcnlwdGlvbl9lbmNfdmFsdWVzX3N1cHBvcnRlZCI6WyJub25lIl0sInJlcXVlc3Rfb2JqZWN0X3NpZ25pbmdfYWxnX3ZhbHVlc19zdXBwb3J0ZWQiOlsiUlMyNTYiLCJSUzUxMiIsIkVTMjU2IiwiRVM1MTIiXSwicmVxdWVzdF9vYmplY3RfZW5jcnlwdGlvbl9hbGdfdmFsdWVzX3N1cHBvcnRlZCI6WyJub25lIl0sInJlcXVlc3Rfb2JqZWN0X2VuY3J5cHRpb25fZW5jX3ZhbHVlc19zdXBwb3J0ZWQiOlsibm9uZSJdLCJkaXNwbGF5X3ZhbHVlc19zdXBwb3J0ZWQiOlsicGFnZSJdLCJjbGFpbV90eXBlc19zdXBwb3J0ZWQiOlsibm9ybWFsIl0sImNsYWltc19zdXBwb3J0ZWQiOltdLCJjbGFpbXNfbG9jYWxlc19zdXBwb3J0ZWQiOltdLCJjbGFpbXNfcGFyYW1ldGVyX3N1cHBvcnRlZCI6dHJ1ZSwicmVxdWVzdF9wYXJhbWV0ZXJfc3VwcG9ydGVkIjp0cnVlLCJyZXF1ZXN0X3VyaV9wYXJhbWV0ZXJfc3VwcG9ydGVkIjp0cnVlLCJyZXF1aXJlX3JlcXVlc3RfdXJpX3JlZ2lzdHJhdGlvbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9kYXBzLmFpc2VjLmZyYXVuaG9mZXIuZGUifQ.LTU-bGR-V5BY4SyCaflcpjgDlzwmAbkME9F8mA0yw8WwhTx89mx9r7tKCtSXHRreG-Le4Kmj2RNrDWRU3UIbkvf5zEFqFkLg3Vhusx0AB7QpNU5wQenKf2r3vYDi0GTxUgYd6J3m2y5J9xwnjo1aIXOcS4Z2Y5TkMG-2PGRpNpqiT1R60qz11FVytum1nPlmeBvUusaavjXen4Fh7Kt8FlG5qzKyuUziiQrbGUd3d1kqvxpZywF-kLIIAh2v2jSVC_vlN22RSRijIvuIECbxp9epZv3eRo1lTRwlqoxvMA_SrR-1n3-BovM8BjkjWaQWGKthGO3qI58EYNomXHu23w"
};